workflows:
  build_apk:
    name: Build Android APK
    max_build_duration: 60
    instance_type:mac_mini
    scripts:
      - name: Clean project
        script: |
          ./gradlew clean
      - name: Build Release APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
